
services:
  # 1. The Database
  # db:
  #   image: postgres:15-alpine
  #   container_name: zakah_db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_NAME}
  #   ports:
  #     - "${DB_PORT}:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - zakah_network

  # 2. The Backend API
  backend:
    build: ./backend  # Tells Docker to build the Dockerfile in /backend
    container_name: zakah_backend
    restart: always
    # depends_on:
    #   - db
    environment:
      # DB_USER: ${DB_USER}
      # DB_PASSWORD: ${DB_PASSWORD}
      # DB_NAME: ${DB_NAME}
      # DB_PORT: 5432
      # # IMPORTANT: In Docker, the host is the Service Name ("db"), not localhost!
      # DB_HOST: db 
      APISED_SECRET_KEY: ${APISED_SECRET_KEY}
    ports:
      - "8080:8080"
    networks:
      - zakah_network

  # 3. The Frontend UI
  frontend:
    build: ./frontend # Tells Docker to build the Dockerfile in /frontend
    container_name: zakah_frontend
    restart: always
    ports:
      - "5173:80" # Map localhost:5173 to container's port 80 (Nginx)
    networks:
      - zakah_network

  # # 4. Database UI (Optional)
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "8081:8080"
  #   networks:
  #     - zakah_network

# volumes:
#   postgres_data:

# Jenkins Service...

  jenkins:
      build: ./jenkins-docker 
      container_name: zakah_jenkins
      restart: always
      user: root # ⚠️ Needed to allow Jenkins to access the Docker Socket
      ports:
        - "9090:8080" # Laptop Port 9090 -> Jenkins Port 8080
        - "50000:50000"
      volumes:
        - jenkins_home:/var/jenkins_home
        #  THE MAGIC: Allows Jenkins (inside docker) to run Docker commands (on your laptop)
        - /var/run/docker.sock:/var/run/docker.sock

networks:
  zakah_network:
    driver: bridge

volumes:
  jenkins_home: 